# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u50TV7TuyC72k94l7zyZz9SuozMIV92T
"""

import gradio as gr
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import os

# --- 1. CONFIGURATION ---

CLASS_NAMES = [
    'Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy',
    'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy',
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_',
    'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot',
    'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy',
    'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy',
    'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight',
    'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy',
    'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy',
    'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold',
    'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite',
    'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus',
    'Tomato___healthy'
]

DEVICE = torch.device("cpu")

# --- 2. MODEL LOADERS ---
def get_resnet():
    model = models.resnet18(weights=None)
    model.fc = nn.Linear(model.fc.in_features, 38) # Must be 38
    # Using ./ to ensure Hugging Face finds the file in the current directory
    if os.path.exists("ResNet18_final.pth"):
        model.load_state_dict(torch.load("ResNet18_final.pth", map_location=DEVICE))
    model.eval()
    return model

def get_effnet():
    model = models.efficientnet_b0(weights=None)
    model.classifier[1] = nn.Linear(model.classifier[1].in_features, 38) # Must be 38
    if os.path.exists("EfficientNet_final.pth"):
        model.load_state_dict(torch.load("EfficientNet_final.pth", map_location=DEVICE))
    model.eval()
    return model

# Initialize models
resnet_model = get_resnet()
effnet_model = get_effnet()

# --- 3. PREDICTION FUNCTION ---
def predict_image(img):
    if img is None: return None, None

    # Matching transforms from testing script
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    img_tensor = transform(img).unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        # ResNet Prediction
        res_out = resnet_model(img_tensor)
        res_probs = torch.nn.functional.softmax(res_out[0], dim=0)

        # EfficientNet Prediction
        eff_out = effnet_model(img_tensor)
        eff_probs = torch.nn.functional.softmax(eff_out[0], dim=0)

    res_results = {CLASS_NAMES[i]: float(res_probs[i]) for i in range(len(CLASS_NAMES))}
    eff_results = {CLASS_NAMES[i]: float(eff_probs[i]) for i in range(len(CLASS_NAMES))}

    return res_results, eff_results

# --- 4. GRADIO INTERFACE ---
with gr.Blocks() as demo:
    gr.Markdown("# 🌿 Plant Disease AI Scanner")
    with gr.Row():
        with gr.Column():
            input_img = gr.Image(type="pil")
            btn = gr.Button("Predict")
        with gr.Column():
            res_label = gr.Label(num_top_classes=3, label="ResNet18 Prediction")
            eff_label = gr.Label(num_top_classes=3, label="EfficientNet-B0 Prediction")

    btn.click(predict_image, inputs=input_img, outputs=[res_label, eff_label])

demo.launch()
